laundry/urls.py
from django.urls import path

from . import views

app_name = "laundry"

urlpatterns = [
    path('', views.read_laundry, name='read_laundry'),
    path('update/', views.update_laundry, name='update_laundry'),
    path('create/', views.create_laundry, name='create_laundry'),
    path('delete/', views.delete_laundry, name='delete_laundry')
]

status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('', views.daftar_status, name='daftar_status'),
]

tk_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
    path('transaksi-laundry/', include('transaksi_laundry.urls')),
    path('layanan/', include('layanan.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('status/', include('status.urls')),
    path('transaksi-topup-dpay/', include('transaksi_topup_dpay.urls'),),
    path('daftar-laundry/', include('laundry.urls')),
    path('item/', include('create_item.urls')),
    path('status-transaksi/', include('status_transaksi.urls'))
]

laundry/models.py
from django.db import models

# Create your models here.

laundry/views.py
import datetime
from django.db import connection
from django.shortcuts import redirect, render

# Create your views here.


def read_laundry(request):
    if request.session["user_role"] in ["staff", "pelanggan"]:
        data = []
        context = {}
        # mengambil semua daftar laundry
        with connection.cursor() as c:
            if request.session["user_role"] == "pelanggan":
                email = request.session["user_email"]
                c.execute(f"select * from daftar_laundry where email = '{email}'")
            else:
                c.execute("select * from daftar_laundry")
            dataSQL = c.fetchall()

            # convert date object to str (date object ada di index ke-1)
            for x in dataSQL:
                data.append((x[0], str(x[1]), x[2], x[3], x[4]))
            context["data"] = data
        return render(request, 'laundry/daftar_laundry.html', context)


def update_laundry(request):
    if request.session["user_role"] == "staff":
        context = {}
        if request.method == "GET":
            # jika data ini ada di parameter get
            try:
                context["email"] = request.GET["email"]
                context["tanggal"] = request.GET["tanggal"]
                context["no_urut"] = request.GET["no_urut"]
                context["jumlah"] = request.GET["jumlah"]
                context["kode"] = request.GET["kode"]
            # jika tidak ada
            except:
                return redirect('laundry:read_laundry')
            # mengambil semua kode item
            with connection.cursor() as c:
                c.execute("select * from item")
                context["daftar_kode"] = c.fetchall()
            return render(request, 'laundry/update_laundry.html', context)
        if request.method == 'POST':
            # melakukan update
            with connection.cursor() as c:
                email = request.POST["email"]
                tanggal = request.POST["tanggal"]
                no_urut = request.POST["no_urut"]
                jumlah_item = request.POST["jumlah_item"]
                kode_item = request.POST["kode_item"]
                command = f"update daftar_laundry set "
                command += f"jumlah_item = {jumlah_item}, kode_item = '{kode_item}' "
                command += f"where email = '{email}' and tanggal_transaksi = '{tanggal}' "
                command += f"and no_urut = {no_urut}"
                # jika update berhasil
                try:
                    c.execute(command)
                    print("success")
                # jika gagal
                except Exception as e:
                    print(e)
            return redirect('laundry:read_laundry')


def delete_laundry(request):
    if request.session["user_role"] == "staff":
        if request.method == "POST":
            with connection.cursor() as c:
                email = request.POST["email"]
                tanggal = request.POST["tanggal"]
                no_urut = request.POST["no_urut"]
                command = f"delete from daftar_laundry where email = '{email}' and "
                command += f"tanggal_transaksi = '{tanggal}' and no_urut = {no_urut}"
                try:
                    c.execute(command)
                    print("success")
                except Exception as e:
                    print(e)
                return redirect('laundry:read_laundry')


def create_laundry(request):
    if request.session["user_role"] == "staff":
        context = {}
        if request.method == 'POST':
            try:
                email = request.POST["email"]
                tanggal = request.POST["tanggal"]
                jumlah_item = request.POST["jumlah_item"]
                kode_item = request.POST["kode_item"]
                # mencari max no_urut
                no_urut = 1
                with connection.cursor() as c:
                    # mengambil nomor urut terbesar terakhir
                    c.execute(
                        f"select max(no_urut) from daftar_laundry where email = '{email}'")
                    row = c.fetchone()
                    # jika table pelanggan sudah ada isinya
                    if row[0] != None:
                        no_urut = str(int(row[0]) + 1)

                # insert data
                with connection.cursor() as c:
                    command = "INSERT INTO daftar_laundry VALUES "
                    command += str((str(email), str(tanggal), no_urut,
                                    jumlah_item, str(kode_item)))
                    c.execute(command)
            except Exception as e:
                print(e)
                context["error"] = "Data yang Anda masukkan tidak valid mohon cek kembali"
                # mengambil semua kode
                with connection.cursor() as c:
                    c.execute("select * from item")
                    context["daftar_kode"] = c.fetchall()
                # mengambil semua email
                with connection.cursor() as c:
                    c.execute("select email from pelanggan")
                    context["daftar_email"] = c.fetchall()
                return render(request, 'laundry/create_laundry.html', context)
            return redirect('laundry:read_laundry')
        else:
            data = []
            # mengambil semua kode
            with connection.cursor() as c:
                c.execute("select * from item")
                context["daftar_kode"] = c.fetchall()
            # mengambil semua email
            with connection.cursor() as c:
                c.execute("select email, tanggal from transaksi_laundry")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data.append((x[0], str(x[1])))
                context["data"] = data
            return render(request, 'laundry/create_laundry.html', context)

laundry/templates/laundry/create_laundry.html
{% extends 'base.html' %} {% block content %}
<h3 class="mt-5 text-center">Buat daftar Laundry</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'laundry:create_laundry' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <select name="email" id="email" class="form-control" required>
        <option selected disabled>Pilih...</option>
        {% for d in data  %}
        <option value="{{ d.0 }}">{{ d.0 }}</option>
        {% endfor %}
      </select>
      <small class="form-text text-danger">{{ error }}</small>
    </div>
    <div class="form-group">
      <label for="tanggal">Tanggal Transaksi</label>
      <select name="tanggal" id="tanggal" class="form-control" required>
        <option selected disabled>Pilih...</option>
        <div id="select-tanggal">
          {% for d in data  %}
          <option class="option-tanggal d-none" data-email="{{ d.0 }}" value="{{ d.1 }}">{{ d.1 }}</option>
          {% endfor %}
          </div>
      </select>
    </div>
    <div class="form-group">
      <label for="jumlah_item">Jumlah Item.</label>
      <input
        required
        type="number"
        class="form-control"
        id="jumlah_item"
        name="jumlah_item"
      />
    </div>
    
    <div class="form-group">
      <label for="kode_item">Kode Item</label>
      <select name="kode_item" id="kode_item" class="form-control" required>
        <option selected disabled>Pilih...</option>
        {% for k in daftar_kode %}
        <option value="{{ k.0 }}">{{ k.0 }} : {{ k.1 }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">
        Buat Daftar Laundry
      </button>
    </div>
  </form>
</div>
{% endblock content %}

{% block js %}
<script>
  $('select#email').change(() => {
    $('.option-tanggal').addClass('d-none')
    $('.option-tanggal').each((i, el) => {
      if ($(el).data("email") == $('select#email').val()) {
        $(el).removeClass('d-none')
      }
    })
  })
</script>
{% endblock js %}

laundry/templates/laundry/daftar_laundry.html
{% extends 'base.html' %} {% block css %}
<style>
  #table-container {
    width: 100%;
    overflow-x: auto !important;
  }
  table {
    width: 95% !important;
  }
</style>
{% endblock css %} {% block content %}
<h3 class="text-center mt-5">Daftar Laundry</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Tanggal</th>
        <th scope="col">No Urut</th>
        <th scope="col">
          Jumlah <br />
          Item
        </th>
        <th scope="col">
          Kode <br />
          Item
        </th>
        {% if request.session.user_role == 'staff' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for laundry in data %}  
      <tr>
        <td>{{ laundry.0 }}</td>
        <td>{{ laundry.1 }}</td>
        <td>{{ laundry.2 }}</td>
        <td>{{ laundry.3 }}</td>
        <td>{{ laundry.4 }}</td>
        {% if request.session.user_role == 'staff' %}          
        <td>
          <div class="d-flex">
            <form action="{% url 'laundry:update_laundry' %}" method="get">
              <input type="email" name="email" value="{{ laundry.0 }}" hidden>
              <input type="datetime" name="tanggal" value="{{ laundry.1 }}" hidden>
              <input type="number" name="no_urut" value="{{ laundry.2 }}" hidden>
              <input type="number" name="jumlah" value="{{ laundry.3 }}" hidden>
              <input type="text" name="kode" value="{{ laundry.4 }}" hidden>
              <button class="btn btn-primary mr-2">Update</button>
            </form>
            <form action="{% url 'laundry:delete_laundry' %}" method="post">
              {% csrf_token %}
              <input type="email" name="email" value="{{ laundry.0 }}" hidden>
              <input type="datetime" name="tanggal" value="{{ laundry.1 }}" hidden>
              <input type="number" name="no_urut" value="{{ laundry.2 }}" hidden>
              <button class="btn btn-delete btn-danger">Delete</button>
            </form>
          </div>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

laundry/templates/laundry/update_laundry.html
{% extends 'base.html' %} {% block content %}
<h3 class="mt-5 text-center">Update Laundry</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'laundry:update_laundry' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <input
        readonly
        required
        value="{{ email }}"
        type="email"
        class="form-control"
        id="email"
        name="email"
      />
    </div>
    <div class="form-group">
      <label for="tanggal_transaksi">Tanggal Transaksi</label>
      <input
        readonly
        required
        value="{{ tanggal }}"
        type="datetime"
        class="form-control"
        id="tanggal_transaksi"
        name="tanggal"
      />
    </div>
    <div class="form-group">
      <label for="no_urut">Nomor Urut</label>
      <input
        required
        readonly
        value="{{ no_urut }}"
        type="number"
        class="form-control"
        id="no_urut"
        name="no_urut"
      />
    </div>
    <div class="form-group">
      <label for="jumlah_item">Jumlah Item</label>
      <input
        required
        value="{{ jumlah }}"
        type="number"
        class="form-control"
        id="jumlah_item"
        name="jumlah_item"
      />
    </div>
    <div class="form-group">
      <label for="kode_item">Kode Item</label>
      <select name="kode_item" id="kode_item" class="form-control" required>
        {% for k in daftar_kode %}
        <option {% if k.0 == kode %}selected{% endif %} value="{{ k.0 }}">{{ k.0 }} : {{ k.1 }}</option>
        {% endfor %}
      </select>
    </div>
  
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">Update</button>
    </div>
  </form>
</div>
{% endblock content %}

{% block js %}
  <script>
    window.history.replaceState({}, document.title, "/daftar-laundry/update/");
  </script>
{% endblock js %} 