status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('', views.daftar_status, name='daftar_status'),
]

testimoni/urls.py
from django.urls import path

from . import views

app_name = "testimoni"

urlpatterns = [
    path('', views.read_testimoni, name='read_testimoni'),
    path('update/', views.update_testimoni, name='update_testimoni'),
    path('create/', views.create_testimoni, name='create_testimoni'),
    path('delete/', views.delete_testimoni, name='delete_testimoni'),
]

tk_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
    path('transaksi-laundry/', include('transaksi_laundry.urls')),
    path('layanan/', include('layanan.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('status/', include('status.urls')),
    path('transaksi-topup-dpay/', include('transaksi_topup_dpay.urls'),),
    path('daftar-laundry/', include('laundry.urls')),
    path('item/', include('create_item.urls')),
    path('status-transaksi/', include('status_transaksi.urls'))
]

testimoni/models.py
from django.db import models

# Create your models here.

testimoni/views.py
import datetime
from django.db import connection
from django.shortcuts import redirect, render

# Create your views here.


def read_testimoni(request):
    if request.session["user_role"] in ["staff", "pelanggan", "kurir"]:
        data = []
        context = {}
        # mengambil semua testimoni
        with connection.cursor() as c:
            c.execute("select * from testimoni")
            dataSQL = c.fetchall()
            # convert date object to str (date object ada di index ke-1 dan ke-2)
            for x in dataSQL:
                data.append((x[0], str(x[1]), str(x[2]), x[3], x[4]))
            context["data"] = data
        return render(request, 'testimoni/daftar_testimoni.html', context)


def update_testimoni(request):
    if request.session["user_role"] == "pelanggan":
        context = {}
        if request.method == "GET":
            # jika data ini ada di parameter get
            try:
                context["email"] = request.GET["email"]
                context["tanggalTransaksi"] = request.GET["tanggalTransaksi"]
                context["tanggalTestimoni"] = request.GET["tanggalTestimoni"]
                context["status"] = request.GET["status"]
                context["rating"] = request.GET["rating"]
            # jika tidak ada
            except:
                return redirect('testimoni:read_testimoni')
            return render(request, 'testimoni/update_testimoni.html', context)
        if request.method == 'POST':
            # melakukan update
            with connection.cursor() as c:
                email = request.POST["email"]
                tanggalTransaksi = request.POST["tanggalTransaksi"]
                tanggalTestimoni = datetime.datetime.now()
                status = request.POST["status"]
                rating = request.POST["rating"]
                command = f"update testimoni set rating = {rating}, "
                command += f"tanggal_testimoni = '{tanggalTestimoni}', status = '{status}' "
                command += f"where email = '{email}' and tanggal_transaksi = '{tanggalTransaksi}'"
                # jika update berhasil
                try:
                    c.execute(command)
                    print("success")
                # jika gagal
                except Exception as e:
                    print(e)
            return redirect('testimoni:read_testimoni')

def delete_testimoni(request):
    if request.session["user_role"] == "pelanggan":
        if request.method == "POST":
            with connection.cursor() as c:
                email = request.POST["email"]
                tanggalTransaksi = request.POST["tanggalTransaksi"]
                tanggalTestimoni = request.POST["tanggalTestimoni"]
                command = f"delete from testimoni where email = '{email}' and "
                command += f"tanggal_transaksi = '{tanggalTransaksi}' and tanggal_testimoni = '{tanggalTestimoni}' "
                try:
                    c.execute(command)
                    print("success")
                except Exception as e:
                    print(e)
                return redirect('testimoni:read_testimoni')

def create_testimoni(request):
    if request.session["user_role"] == "pelanggan":
        context = {}
        data = []
        if request.method == 'POST':
            try:
                email = request.POST["email"]
                tanggalTransaksi = request.POST["tanggalTransaksi"]
                tanggalTestimoni = datetime.datetime.now()
                status = request.POST["status"]
                rating = request.POST["rating"]

                # insert data
                with connection.cursor() as c:
                    command = "INSERT INTO testimoni VALUES "
                    command += str((str(email), str(tanggalTransaksi), str(tanggalTestimoni),
                                    str(status), rating))
                    c.execute(command)
            except Exception as e:
                print(e)
                context["error"] = "Data yang Anda masukkan tidak valid mohon cek kembali"
                #Ambil query lagi untuk di pass pada dropdown
                with connection.cursor() as c:
                    c.execute("select email, tanggal from transaksi_laundry")
                    dataSQL = c.fetchall()
                    for x in dataSQL:
                        data.append((x[0], str(x[1])))
                    context["data"] = data
                return render(request, 'testimoni/create_testimoni.html', context)
            return redirect('testimoni:read_testimoni')
        else:
            # mengambil semua email
            with connection.cursor() as c:
                c.execute("select email, tanggal from transaksi_laundry")
                dataSQL = c.fetchall()
                for x in dataSQL:
                    data.append((x[0], str(x[1])))
                context["data"] = data
            return render(request, 'testimoni/create_testimoni.html', context)

testimoni/templates/testimoni/create_testimoni.html
{% extends 'base.html' %} {% block content %}
<h3 class="mt-5 text-center">FORM TESTIMONI</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'testimoni:create_testimoni' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <select name="email" id="email" class="form-control" required>
        <option selected disabled>Pilih...</option>
        {% for d in data  %}
        <option value="{{ d.0 }}">{{ d.0 }}</option>
        {% endfor %}
      </select>
      <small class="form-text text-danger">{{ error }}</small>
    </div>
    <div class="form-group">
      <label for="tanggalTransaksi">Tanggal Transaksi</label>
      <select name="tanggalTransaksi" id="tanggalTransaksi" class="form-control" required>
        <option selected disabled>Pilih...</option>
        <div id="select-tanggal">
          {% for d in data  %}
          <option class="option-tanggal d-none" data-email="{{ d.0 }}" value="{{ d.1 }}">{{ d.1 }}</option>
          {% endfor %}
          </div>
      </select>
    </div>

    <div class="form-group">
      <label for="status">Status</label>
      <input
        required
        type="text"
        class="form-control"
        id="status"
        name="status"
      />
    </div>
    <div class="form-group">
      <label for="rating">Rating</label>
      <input
        required
        type="number"
        class="form-control"
        id="rating"
        name="rating"
        min="1"
        max="5"
      />
    </div>
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">
        SUBMIT
      </button>
    </div>
  </form>
</div>
{% endblock content %}

{% block js %}
<script>
  $('select#email').change(() => {
    $('.option-tanggal').addClass('d-none')
    $('.option-tanggal').each((i, el) => {
      if ($(el).data("email") == $('select#email').val()) {
        $(el).removeClass('d-none')
      }
    })
  })
</script>
{% endblock js %}

testimoni/templates/testimoni/daftar_testimoni.html
{% extends 'base.html' %} {% block css %}
<style>
  #table-container {
    width: 100%;
    overflow-x: auto !important;
  }
  table {
    width: 95% !important;
  }
  .container {
    height: 200px;
    position: relative;
    border: 3px solid green;
  }

  .vertical-center {
    margin: 0;
    position: absolute;
    top: 50%;
    -ms-transform: translateY(-50%);
    transform: translateY(-50%);
  }
</style>
{% endblock css %} {% block content %}
<h3 class="text-center mt-5">Daftar Testimoni</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Tanggal Transaksi</th>
        <th scope="col">Tanggal Testimoni</th>
        <th scope="col">Status</th>
        <th scope="col">Rating</th>
        {% if request.session.user_role == 'pelanggan' %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for testimoni in data %}
      <tr>
        <td>{{ testimoni.0 }}</td>
        <td>{{ testimoni.1 }}</td>
        <td>{{ testimoni.2 }}</td>
        <td>{{ testimoni.3 }}</td>
        <td>{{ testimoni.4 }}</td>
        {% if request.session.user_role == "pelanggan" %}          
        {% if request.session.user_email == testimoni.0 %}
        <td>
          <div class="d-flex">
            <form action="{% url 'testimoni:update_testimoni' %}" method="get">
              <input type="email" name="email" value="{{ testimoni.0 }}" hidden>
              <input type="datetime" name="tanggalTransaksi" value="{{ testimoni.1 }}" hidden>
              <input type="datetime" name="tanggalTestimoni" value="{{ testimoni.2 }}" hidden>
              <input type="text" name="status" value="{{ testimoni.3 }}" hidden>
              <input type="number" name="rating" value="{{ testimoni.4 }}" hidden>
              <button class="btn btn-primary mr-2">Update</button>
            </form>
            <form action="{% url 'testimoni:delete_testimoni' %}" method="post">
              {% csrf_token %}
              <input type="email" name="email" value="{{ testimoni.0 }}" hidden>
              <input type="datetime" name="tanggalTransaksi" value="{{ testimoni.1 }}" hidden>
              <input type="datetime" name="tanggalTestimoni" value="{{ testimoni.2}} " hidden>
              <input type="text" name="status" value="{{ testimoni.3 }}" hidden>
              <input type="number" name="rating" value="{{ testimoni.4 }}" hidden>
              <button class="btn btn-delete btn-danger">Delete</button>
            </form>
          </div>
        </td>
        {% else %}
        <td>Not Allowed</td>
        {% endif %}
        {% endif %}

      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% if request.session.user_role == 'pelanggan' %}
<div class="d-flex justify-content-center">
  <a class="btn btn-primary mt-4" href="{%url 'testimoni:create_testimoni' %}"> Buat Testimoni </a>
</div>
{% endif %}

{% endblock content %}

testimoni/templates/testimoni/update_testimoni.html
{% extends 'base.html' %} {% block content %}
<h3 class="mt-5 text-center">FORM UPDATE TESTIMONI</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'testimoni:update_testimoni' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email</label>
      <input
        readonly
        required
        value="{{ email }}"
        type="email"
        class="form-control"
        id="email"
        name="email"
      />
    </div>
    <div class="form-group">
      <label for="tanggalTransaksi">Tanggal Transaksi</label>
      <input
        readonly
        required
        value="{{ tanggalTransaksi }}"
        type="datetime"
        class="form-control"
        id="tanggalTransaksi"
        name="tanggalTransaksi"
      />
    </div>
    <div class="form-group">
      <label for="status">Status</label>
      <input
        required
        value="{{ status }}"
        type="text"
        class="form-control"
        id="status"
        name="status"
      />
    </div>
    <div class="form-group">
      <label for="rating">Rating</label>
      <input
        required
        value="{{ rating }}"
        type="number"
        class="form-control"
        id="rating"
        name="rating"
        min="1"
        max="5"
      />
    </div>
    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">
        UPDATE
      </button>
    </div>
  </form>
</div>
{% endblock content %}

{% block js %}
  <script>
    window.history.replaceState({}, document.title, "/daftar-testimoni/update/");
  </script>
{% endblock js %} 