autentikasi/urls.py
from django.urls import path

from . import views

app_name = "autentikasi"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout')
]

laundry/urls.py
from django.urls import path

from . import views

app_name = "laundry"

urlpatterns = [
    path('', views.read_laundry, name='read_laundry'),
    path('update/', views.update_laundry, name='update_laundry'),
    path('create/', views.create_laundry, name='create_laundry'),
    path('delete/', views.delete_laundry, name='delete_laundry')
]

layanan/urls.py
from django.urls import path

from . import views

app_name = "layanan"

urlpatterns = [
    path('', views.read_layanan, name='read_layanan'),
    path('update/', views.update_layanan, name='update_layanan'),
]

status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('', views.daftar_status, name='daftar_status'),
]

testimoni/urls.py
from django.urls import path

from . import views

app_name = "testimoni"

urlpatterns = [
    path('', views.read_testimoni, name='read_testimoni'),
    path('update/', views.update_testimoni, name='update_testimoni'),
    path('create/', views.create_testimoni, name='create_testimoni'),
    path('delete/', views.delete_testimoni, name='delete_testimoni'),
]

tk_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
    path('transaksi-laundry/', include('transaksi_laundry.urls')),
    path('layanan/', include('layanan.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('status/', include('status.urls')),
    path('transaksi-topup-dpay/', include('transaksi_topup_dpay.urls'),),
    path('daftar-laundry/', include('laundry.urls')),
    path('item/', include('create_item.urls')),
    path('status-transaksi/', include('status_transaksi.urls'))
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% block meta %}
      
    {% endblock meta %}
    <!-- Custom CSS -->
    {% block css %}{% endblock css %}
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock content %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <!-- Optional JavaScript -->
    {% block js %}{% endblock js %}
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <noscript>Your browser does not support JavaScript!</noscript>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'autentikasi:home' %}">SILAU</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if request.session.user_email %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Transaksi Laundry
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.user_role == 'staff' %}
          <a class="dropdown-item" href="{% url 'transaksi_laundry:create_transaksi' %}">Buat Transaksi laundry</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'transaksi_laundry:read_transaksi' %}">Daftar Transaksi laundry</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Transaksi Top Up DPAY
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.user_role != 'kurir' %}
          <a class="dropdown-item" href="{% url 'transaksi_topup_dpay:create_transaksi_topup_dpay' %}">Buat Transaksi TOP UP</a>  
          {% endif %}
          <a class="dropdown-item" href="{% url 'transaksi_topup_dpay:daftar_transaksi_topup_dpay' %}">Daftar Transaksi TOP UP</a>
        </div>
      </li>
      {% if request.session.user_role == 'staff' %}
      <li class="nav-item dropdown"> 
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Daftar Laundry
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'laundry:create_laundry' %}">Buat Daftar Laundry</a>
          <a class="dropdown-item" href="{% url 'laundry:read_laundry' %}">Daftar Laundry</a>
        </div>
      </li>
      {% else %}
      {% if request.session.user_role == 'pelanggan' %}        
      <li class="nav-item">
        <a class="nav-link" href="{% url 'laundry:read_laundry' %}">Daftar Laundry</a>
      </li>
      {% endif %}
      {% endif %}
      {% if request.session.user_role != 'kurir' %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'layanan:read_layanan' %}">Tarif Layanan</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testimoni:read_testimoni' %}">Testimoni</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'status:daftar_status' %}">Status</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'status_transaksi:read_status_transaksi' %}">Status Transaksi</a>
      </li>
      {% if request.session.user_role == 'staff' %}
      <li class="nav-item dropdown"> 
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Item
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'item:create_item' %}">Buat Item</a>
          <a class="dropdown-item" href="{% url 'item:read_item' %}">Daftar Item</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'item:read_item' %}">Daftar Item</a>
      </li>
      {% endif %}
      {% endif %}
    </ul>
      <p class="nav-link text-dark font-weight-bold mb-0">{{ request.session.user_role.capitalize }}</p>
    {% if request.session.user_email %}
    <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'autentikasi:logout' %}">Logout</a>
    {% else %}
    <a class="btn btn-outline-secondary my-2 my-sm-0" href="{% url 'autentikasi:login' %}">Login</a>
    <a class="btn btn-outline-success my-2 ml-2 my-sm-0" href="{% url 'autentikasi:register' %}">Register</a>
    {% endif %}
  </div>
</nav>