status/urls.py
from django.urls import path
from . import views

app_name = "status"

urlpatterns = [
    path('', views.daftar_status, name='daftar_status'),
]

tk_basdat/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikasi.urls')),
    path('transaksi-laundry/', include('transaksi_laundry.urls')),
    path('layanan/', include('layanan.urls')),
    path('testimoni/', include('testimoni.urls')),
    path('status/', include('status.urls')),
    path('transaksi-topup-dpay/', include('transaksi_topup_dpay.urls'),),
    path('daftar-laundry/', include('laundry.urls')),
    path('item/', include('create_item.urls')),
    path('status-transaksi/', include('status_transaksi.urls'))
]

transaksi_topup_dpay/urls.py
from django.urls import path
from . import views

app_name = "transaksi_topup_dpay"

urlpatterns = [
    path('', views.daftar_transaksi_topup_dpay, name='daftar_transaksi_topup_dpay'),
    path('create/', views.create_transaksi_topup_dpay, name='create_transaksi_topup_dpay'),
    path('update/', views.update_transaksi_topup_dpay, name='update_transaksi_topup_dpay'),
    path('update/<str:email>/<str:tanggal>', views.update_transaksi_topup_dpay, name='update_transaksi_topup_dpay'),
    path('delete/<str:email>/<str:tanggal>', views.delete_transaksi_topup_dpay, name='delete_transaksi_topup_dpay'),
]

transaksi_topup_dpay/models.py
from django.db import models

# Create your models here.

transaksi_topup_dpay/forms.py
from django import forms
from datetime import datetime

class CreateTransaksiTopupDpayForm(forms.Form):
    def __init__(self, email_choices=None, *args, **kwargs):
        super(CreateTransaksiTopupDpayForm, self).__init__(*args, **kwargs)
        self.fields['email'].choices = email_choices

    email = forms.ChoiceField(label='Email:', required=True, choices=())
    tanggal = forms.DateTimeField(label='Tanggal:', widget=forms.HiddenInput(), initial=datetime.now(), required=True)
    nominal = forms.DecimalField(label='Nominal:', required=True)

class UpdateTransaksiTopupDpayForm(forms.Form):
    email = forms.EmailField(label='Email:', disabled=True, required=True)
    tanggal = forms.DateTimeField(label='Tanggal:', disabled=True, required=True)
    nominal = forms.DecimalField(label='Nominal:', required=True)

transaksi_topup_dpay/views.py
from django.shortcuts import render, redirect
from django.db import connection
from .forms import CreateTransaksiTopupDpayForm, UpdateTransaksiTopupDpayForm

"""
# This is mockup code
def daftar_transaksi_topup_dpay(request):
    return render(request, 'transaksi_topup_dpay/daftar_transaksi_topup_dpay.html')

def create_transaksi_topup_dpay(request):
    if request.method == 'POST':
        return redirect('transaksi_topup_dpay:daftar_transaksi_topup_dpay')
    return render(request, 'transaksi_topup_dpay/create_transaksi_topup_dpay.html')

def update_transaksi_topup_dpay(request):
    if request.method == 'POST':
        return redirect('transaksi_topup_dpay:daftar_transaksi_topup_dpay')
    return render(request, 'transaksi_topup_dpay/update_transaksi_topup_dpay.html')

# Uncomment only after database schema is in place
"""

def daftar_transaksi_topup_dpay(request):
    with connection.cursor() as cursor:
        cursor.execute("select * from transaksi_topup_dpay")
        data = []
        for x in cursor.fetchall():
            data.append((str(x[0]), str(x[1]), x[2]))
        context = {"daftar_transaksi_topup_dpay" : data}
    return render(request, "transaksi_topup_dpay/daftar_transaksi_topup_dpay.html", context)

def create_transaksi_topup_dpay(request):
    with connection.cursor() as cursor:
        cursor.execute("select email from transaksi_topup_dpay")
        choice =  [(_[0], _[0]) for _ in cursor.fetchall()]
        cursor.execute("select email, tanggal, nominal from transaksi_topup_dpay")

        if request.method == "POST":
            form = CreateTransaksiTopupDpayForm(choice, request.POST)
            if form.is_valid():
                cursor.execute("insert into transaksi_topup_dpay (email, tanggal, nominal) values (%s, %s, %s)",
                    [
                        form.cleaned_data['email'],
                        form.cleaned_data['tanggal'],
                        form.cleaned_data['nominal']
                    ]
                )
                return redirect('transaksi_topup_dpay:daftar_transaksi_topup_dpay')
        else:
            form = CreateTransaksiTopupDpayForm(choice)
        return render(request, 'transaksi_topup_dpay/create_transaksi_topup_dpay.html', {'form' : form})

def update_transaksi_topup_dpay(request, email, tanggal):
    with connection.cursor() as cursor:
        cursor.execute(f"select email, tanggal, nominal from transaksi_topup_dpay where email = '{email}' and tanggal = '{tanggal}'")
        data = cursor.fetchall()[0]
        data_initial = {
            'email' : data[0],
            'tanggal' : data[1],
            'nominal' : data[2]
        }

        if request.method == "POST":
            form = UpdateTransaksiTopupDpayForm(request.POST, initial=data_initial)
            if form.is_valid():
                cursor.execute(f"update transaksi_topup_dpay set nominal = {nominal} where email = '{email}' and tanggal = '{tanggal}'")
                return redirect('transaksi_topup_dpay:daftar_transaksi_topup_dpay')
        else:
            form = UpdateTransaksiTopupDpayForm(initial=data_initial)
        return render(request, 'transaksi_topup_dpay/update_transaksi_topup_dpay.html', {'form' : form})

def delete_transaksi_topup_dpay(request, email, tanggal):
    with connection.cursor() as cursor:
        cursor.execute(f"delete from transaksi_topup_dpay where email = '{email}' and tanggal = '{tanggal}'")
        return render(request, 'transaksi_topup_dpay/daftar_transaksi_topup_dpay.html')

transaksi_topup_dpay/templates/transaksi_topup_dpay/create_transaksi_topup_dpay.html
{% extends 'base.html' %} 
{% block title %} Create Transaksi TOP UP DPAY{% endblock %}
{% block content %}
<h3 class="mt-5 text-center">FORM CREATE TRANSAKSI TOP UP DPAY</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'transaksi_topup_dpay:daftar_transaksi_topup_dpay' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
<!-- This is mockup code
<div class="form-group">
  <label for="email">Email:</label>
  <select name="email" id="email" class="form-control" required>
    <option selected disabled></option>
    <option value="jwild0@moonfruit.com">jwild0@moonfruit.com</option>
    <option value="whender1@shutterfly.com">whender1@shutterfly.com</option>
    <option value="nwitherbed2@stanford.edu">nwitherbed2@stanford.edu</option>
  </select>
</div>
<div class="form-group">
  <label for="nominal">Nominal:</label>
  <input
    required
    type="text"
    class="form-control"
    id="nominal"
    name="nominal"
  />
</div>
-->
    {% for field in form %}
    <div class="form-group">
      {{ field }}
    </div>
    {% endfor %}

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">CREATE</button>
    </div>

  </form>
</div>
{% endblock content %}

transaksi_topup_dpay/templates/transaksi_topup_dpay/daftar_transaksi_topup_dpay.html
{% extends 'base.html' %} {% block css %}
<style>
  #table-container {
    width: 100%;
    overflow-x: auto !important;
  }
  table {
    width: 95% !important;
  }
</style>
{% endblock css %}
{% block title %} Daftar Transaksi TOP UP DPAY{% endblock %}
{% block content %}
<h3 class="text-center mt-5">Daftar Transaksi TOP UP DPAY</h3>
<div id="table-container" class="d-flex justify-content-center">
  <table class="table table-striped mt-3">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Nominal</th>
        {% if request.session.user_role != 'kurir' %}
        <th scope="col">Actions</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
<!-- This is mockup code
      <tr>
        <td>jwild0@moonfruit.com</td>
        <td>2020-01-06 18:29:24</td>
        <td>73300</td>        
        <td>
          {% if request.session.user_role != 'kurir' %}
          <div class="d-flex">
            <a href="{% url 'transaksi_topup_dpay:update_transaksi_topup_dpay' %}" class="btn btn-primary mr-2">Update</a>
            <a href="#" class="btn btn-delete btn-danger">Delete</a>
          </div>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>whender1@shutterfly.com</td>
        <td>2020-08-20 14:39:32</td>
        <td>86200</td>        
        <td>
          {% if request.session.user_role != 'kurir' %}
          <div class="d-flex">
            <a href="{% url 'transaksi_topup_dpay:update_transaksi_topup_dpay' %}" class="btn btn-primary mr-2">Update</a>
            <a href="#" class="btn btn-delete btn-danger">Delete</a>
          </div>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>nwitherbed2@stanford.edu</td>
        <td>2020-05-20 11:23:32</td>
        <td>84700</td>         
        <td>
          {% if request.session.user_role != 'kurir' %}
          <div class="d-flex">
            <a href="{% url 'transaksi_topup_dpay:update_transaksi_topup_dpay' %}" class="btn btn-primary mr-2">Update</a>
            <a href="#" class="btn btn-delete btn-danger">Delete</a>
          </div>
          {% endif %}
        </td>
      </tr>
    -->
      {% for transaksi_topup_dpay in daftar_transaksi_topup_dpay %}
      <tr>
        {% if request.session.user_email == transaksi_topup_dpay.0 and request.session.user_role == 'pelanggan' or request.session.user_role != 'pelanggan' %} 
        <td>{{ transaksi_topup_dpay.0 }}</td>
        <td>{{ transaksi_topup_dpay.1 }}</td>
        <td>{{ transaksi_topup_dpay.2 }}</td>
        <td>
          {% if request.session.user_role != kurir %}
          <div class="d-flex">
            <a href="{% url 'transaksi_topup_dpay:update_transaksi_topup_dpay' email=transaksi_topup_dpay.0 tanggal=transaksi_topup_dpay.1 %}" class="btn btn-primary mr-2">Update</a>
            <a href="{% url 'transaksi_topup_dpay:delete_transaksi_topup_dpay' email=transaksi_topup_dpay.0 tanggal=transaksi_topup_dpay.1 %}" class="btn btn-delete btn-danger">Delete</a>
          </div>
          {% endif %}
        </td>
        {% endif %}
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>

{% if request.session.user_role == 'staff' %}
<div class="d-flex justify-content-center">
  <a class="btn btn-primary mt-4" href="{%url 'transaksi_topup_dpay:create_transaksi_topup_dpay' %}"> Buat Transaksi Top Up DPAY </a>
</div>
{% endif %}

{% endblock content %}

transaksi_topup_dpay/templates/transaksi_topup_dpay/update_transaksi_topup_dpay.html
{% extends 'base.html' %} 
{% block title %} Update Transaksi TOP UP DPAY{% endblock %}
{% block content %}
<h3 class="mt-5 text-center">FORM UPDATE TRANSAKSI TOP UP DPAY</h3>
<div class="d-flex flex-column align-items-center">
  <form
    action="{% url 'transaksi_topup_dpay:daftar_transaksi_topup_dpay' %}"
    method="POST"
    class="col-6 pb-5"
  >
    {% csrf_token %}
<!-- This is mockup code
    <div class="form-group">
        <label for="email">Email:</label>
        <input
          disabled
          required
          value="jwild0@moonfruit.com"
          type="email"
          class="form-control"
          id="email"
          name="email"
        />
      </div>
      <div class="form-group">
        <label for="tanggal">Tanggal:</label>
        <input
          disabled
          required
          value="2020-01-06 18:29:24"
          type="datetime"
          class="form-control"
          id="tanggal"
          name="tanggal"
        />
      </div>
      <div class="form-group">
        <label for="nominal">Nominal:</label>
        <input
          required
          value="73300"
          type="number"
          class="form-control"
          id="nominal"
          name="nominal"
        />
      </div>
-->
    {% for field in form %}
    <div class="form-group">
      {{ field }}
    </div>
    {% endfor %}

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-primary col-12">UPDATE</button>
    </div>

  </form>
</div>
{% endblock content %}